/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminSongListResponseDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * 선택된 아티스트의 곡 목록을 역할(role)과 노래방 번호 정보와 함께 반환합니다.
 * @summary 특정 아티스트의 곡 목록 조회 (관리자용)
 */
export const adminControllerGetArtistSongs = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<AdminSongListResponseDto>(
      {url: `/admin/artists/${id}/songs`, method: 'GET', signal
    },
      );
    }
  



export const getAdminControllerGetArtistSongsQueryKey = (id?: number,) => {
    return [
    `/admin/artists/${id}/songs`
    ] as const;
    }

    
export const getAdminControllerGetArtistSongsQueryOptions = <TData = Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetArtistSongsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetArtistSongs>>> = ({ signal }) => adminControllerGetArtistSongs(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetArtistSongsQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetArtistSongs>>>
export type AdminControllerGetArtistSongsQueryError = unknown


export function useAdminControllerGetArtistSongs<TData = Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetArtistSongs>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetArtistSongs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetArtistSongs<TData = Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetArtistSongs>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetArtistSongs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetArtistSongs<TData = Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 특정 아티스트의 곡 목록 조회 (관리자용)
 */

export function useAdminControllerGetArtistSongs<TData = Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetArtistSongs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetArtistSongsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




