/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponseDto,
  MobileAnonymousLoginDto,
  MobileAuthResponseDto,
  ProfileResponseDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * 새 익명 사용자 생성 및 토큰 발급
 * @summary 익명 로그인
 */
export const authControllerAnonymousLogin = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<AuthResponseDto | AuthResponseDto>(
      {url: `/auth/anonymous`, method: 'POST', signal
    },
      );
    }
  


export const getAuthControllerAnonymousLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAnonymousLogin>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerAnonymousLogin>>, TError,void, TContext> => {

const mutationKey = ['authControllerAnonymousLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerAnonymousLogin>>, void> = () => {
          

          return  authControllerAnonymousLogin()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerAnonymousLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerAnonymousLogin>>>
    
    export type AuthControllerAnonymousLoginMutationError = unknown

    /**
 * @summary 익명 로그인
 */
export const useAuthControllerAnonymousLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAnonymousLogin>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerAnonymousLogin>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerAnonymousLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * deviceId + 서명 기반으로 토큰 발급
 * @summary 앱 익명 로그인
 */
export const authControllerAnonymousMobileLogin = (
    mobileAnonymousLoginDto: MobileAnonymousLoginDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<MobileAuthResponseDto | MobileAuthResponseDto>(
      {url: `/auth/anonymous/mobile`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mobileAnonymousLoginDto, signal
    },
      );
    }
  


export const getAuthControllerAnonymousMobileLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAnonymousMobileLogin>>, TError,{data: MobileAnonymousLoginDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerAnonymousMobileLogin>>, TError,{data: MobileAnonymousLoginDto}, TContext> => {

const mutationKey = ['authControllerAnonymousMobileLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerAnonymousMobileLogin>>, {data: MobileAnonymousLoginDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerAnonymousMobileLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerAnonymousMobileLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerAnonymousMobileLogin>>>
    export type AuthControllerAnonymousMobileLoginMutationBody = MobileAnonymousLoginDto
    export type AuthControllerAnonymousMobileLoginMutationError = unknown

    /**
 * @summary 앱 익명 로그인
 */
export const useAuthControllerAnonymousMobileLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerAnonymousMobileLogin>>, TError,{data: MobileAnonymousLoginDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerAnonymousMobileLogin>>,
        TError,
        {data: MobileAnonymousLoginDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerAnonymousMobileLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Refresh token으로 새 토큰 발급
 * @summary 토큰 갱신
 */
export const authControllerRefresh = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<AuthResponseDto | AuthResponseDto>(
      {url: `/auth/refresh`, method: 'POST', signal
    },
      );
    }
  


export const getAuthControllerRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext> => {

const mutationKey = ['authControllerRefresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefresh>>, void> = () => {
          

          return  authControllerRefresh()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefresh>>>
    
    export type AuthControllerRefreshMutationError = unknown

    /**
 * @summary 토큰 갱신
 */
export const useAuthControllerRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRefresh>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 현재 로그인한 사용자 정보 조회
 * @summary 프로필 조회
 */
export const authControllerGetProfile = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<ProfileResponseDto>(
      {url: `/auth/profile`, method: 'GET', signal
    },
      );
    }
  



export const getAuthControllerGetProfileQueryKey = () => {
    return [
    `/auth/profile`
    ] as const;
    }

    
export const getAuthControllerGetProfileQueryOptions = <TData = Awaited<ReturnType<typeof authControllerGetProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerGetProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetProfile>>> = ({ signal }) => authControllerGetProfile(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerGetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGetProfile>>>
export type AuthControllerGetProfileQueryError = unknown


export function useAuthControllerGetProfile<TData = Awaited<ReturnType<typeof authControllerGetProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGetProfile<TData = Awaited<ReturnType<typeof authControllerGetProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGetProfile<TData = Awaited<ReturnType<typeof authControllerGetProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 프로필 조회
 */

export function useAuthControllerGetProfile<TData = Awaited<ReturnType<typeof authControllerGetProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerGetProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Refresh token 무효화
 * @summary 로그아웃
 */
export const authControllerLogout = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<void | void>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getAuthControllerLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {
          

          return  authControllerLogout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>
    
    export type AuthControllerLogoutMutationError = unknown

    /**
 * @summary 로그아웃
 */
export const useAuthControllerLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    