/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  YoutubeChannelUpdateDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * 선택한 아티스트에 YouTube 채널 ID 또는 @handle 을 연결합니다.
 * @summary 아티스트 YouTube 채널 정보 업데이트
 */
export const youtubeControllerUpdateArtistChannel = (
    alias: string,
    youtubeChannelUpdateDto: YoutubeChannelUpdateDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<unknown | void>(
      {url: `/youtube/update-artist-channel/${alias}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: youtubeChannelUpdateDto, signal
    },
      );
    }
  


export const getYoutubeControllerUpdateArtistChannelMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof youtubeControllerUpdateArtistChannel>>, TError,{alias: string;data: YoutubeChannelUpdateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof youtubeControllerUpdateArtistChannel>>, TError,{alias: string;data: YoutubeChannelUpdateDto}, TContext> => {

const mutationKey = ['youtubeControllerUpdateArtistChannel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof youtubeControllerUpdateArtistChannel>>, {alias: string;data: YoutubeChannelUpdateDto}> = (props) => {
          const {alias,data} = props ?? {};

          return  youtubeControllerUpdateArtistChannel(alias,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type YoutubeControllerUpdateArtistChannelMutationResult = NonNullable<Awaited<ReturnType<typeof youtubeControllerUpdateArtistChannel>>>
    export type YoutubeControllerUpdateArtistChannelMutationBody = YoutubeChannelUpdateDto
    export type YoutubeControllerUpdateArtistChannelMutationError = void

    /**
 * @summary 아티스트 YouTube 채널 정보 업데이트
 */
export const useYoutubeControllerUpdateArtistChannel = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof youtubeControllerUpdateArtistChannel>>, TError,{alias: string;data: YoutubeChannelUpdateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof youtubeControllerUpdateArtistChannel>>,
        TError,
        {alias: string;data: YoutubeChannelUpdateDto},
        TContext
      > => {

      const mutationOptions = getYoutubeControllerUpdateArtistChannelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    