import { Artist, Song, Provider } from './types';

const now = new Date();

export const mrsGreenAppleArtist: Artist = {
  id: 2,
  name: 'Mrs. GREEN APPLE',
  nameKo: '미세스 그린 애플',
  nameNorm: 'mrs green apple',
  pathname: 'mrs-green-apple',
  youtubeChannelUrl: 'https://www.youtube.com/@MrsGREENAPPLE_Official',
  tjSongRequestUrl: 'https://www.tjmedia.com/song/accompaniment_apply?pageNo=1&dt_code=30&singer=Mrs.+GREEN+APPLE',
  createdAt: now,
  updatedAt: now,
};

// Artist ID 2: Songs 2000-2999, KaraokeSongs 2000-2999
export const mrsGreenAppleSongs: Song[] = [
  {
    id: 2000,
    title: '青と夏',
    titleKo: '푸름과 여름',
    titleNorm: 'ao to natsu',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2000, songId: 2000, provider: Provider.TJ, karaokeNo: '68127', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2001, songId: 2000, provider: Provider.KY, karaokeNo: '44466', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2002, songId: 2000, provider: Provider.JOYSOUND, karaokeNo: '430643', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2001,
    title: '点描の唄',
    titleKo: '점묘의 노래',
    titleNorm: 'tenbyo no uta',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2003, songId: 2001, provider: Provider.TJ, karaokeNo: '68141', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2004, songId: 2001, provider: Provider.KY, karaokeNo: '44547', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2005, songId: 2001, provider: Provider.JOYSOUND, karaokeNo: '430642', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2002,
    title: 'ケセラセラ',
    titleKo: '케세라세라',
    titleNorm: 'que sera sera',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2006, songId: 2002, provider: Provider.TJ, karaokeNo: '52844', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2007, songId: 2002, provider: Provider.KY, karaokeNo: '57810', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2008, songId: 2002, provider: Provider.JOYSOUND, karaokeNo: '617082', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2003,
    title: 'ダンスホール',
    titleKo: '댄스홀',
    titleNorm: 'dance hall',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2009, songId: 2003, provider: Provider.TJ, karaokeNo: '68620', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2010, songId: 2003, provider: Provider.KY, karaokeNo: '44808', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2011, songId: 2003, provider: Provider.JOYSOUND, karaokeNo: '499083', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2004,
    title: 'ダーリン',
    titleKo: '달링',
    titleNorm: 'darling',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2012, songId: 2004, provider: Provider.TJ, karaokeNo: '52793', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2013, songId: 2004, provider: Provider.KY, karaokeNo: '57823', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2014, songId: 2004, provider: Provider.JOYSOUND, karaokeNo: '633793', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2005,
    title: 'インフェルノ',
    titleKo: '인페르노',
    titleNorm: 'inferno',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2015, songId: 2005, provider: Provider.TJ, karaokeNo: '68095', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2016, songId: 2005, provider: Provider.KY, karaokeNo: '44455', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2017, songId: 2005, provider: Provider.JOYSOUND, karaokeNo: '440807', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2006,
    title: '天国',
    titleKo: '천국',
    titleNorm: 'tengoku',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2018, songId: 2006, provider: Provider.TJ, karaokeNo: '52924', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2019, songId: 2006, provider: Provider.KY, karaokeNo: '57798', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2020, songId: 2006, provider: Provider.JOYSOUND, karaokeNo: '636457', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2007,
    title: 'breakfast',
    titleKo: 'breakfast',
    titleNorm: 'breakfast',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2021, songId: 2007, provider: Provider.TJ, karaokeNo: '52935', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2022, songId: 2007, provider: Provider.JOYSOUND, karaokeNo: '637422', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2008,
    title: 'ライラック',
    titleKo: '라일락',
    titleNorm: 'lilac',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2023, songId: 2008, provider: Provider.TJ, karaokeNo: '68461', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2024, songId: 2008, provider: Provider.KY, karaokeNo: '75996', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2025, songId: 2008, provider: Provider.JOYSOUND, karaokeNo: '625838', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2009,
    title: 'Soranji',
    titleKo: 'Soranji',
    titleNorm: 'soranji',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2026, songId: 2009, provider: Provider.TJ, karaokeNo: '68736', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2027, songId: 2009, provider: Provider.KY, karaokeNo: '44878', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2028, songId: 2009, provider: Provider.JOYSOUND, karaokeNo: '612122', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2010,
    title: 'クスシキ',
    titleKo: '쿠스시키',
    titleNorm: 'kusushiki',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2029, songId: 2010, provider: Provider.TJ, karaokeNo: '52834', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2030, songId: 2010, provider: Provider.KY, karaokeNo: '57783', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2031, songId: 2010, provider: Provider.JOYSOUND, karaokeNo: '635504', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2011,
    title: '僕のこと',
    titleKo: '나라는 것',
    titleNorm: 'boku no koto',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2032, songId: 2011, provider: Provider.TJ, karaokeNo: '68248', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2033, songId: 2011, provider: Provider.KY, karaokeNo: '44894', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2034, songId: 2011, provider: Provider.JOYSOUND, karaokeNo: '435229', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2012,
    title: '夏の影',
    titleKo: '여름의 그림자',
    titleNorm: 'natsu no kage',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2035, songId: 2012, provider: Provider.JOYSOUND, karaokeNo: '639551', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2013,
    title: 'familie',
    titleKo: 'familie',
    titleNorm: 'familie',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2036, songId: 2013, provider: Provider.TJ, karaokeNo: '52721', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2037, songId: 2013, provider: Provider.KY, karaokeNo: '76522', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2038, songId: 2013, provider: Provider.JOYSOUND, karaokeNo: '629477', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2014,
    title: 'ナハトムジーク',
    titleKo: '나흐트무지크',
    titleNorm: 'nacht musik',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2039, songId: 2014, provider: Provider.JOYSOUND, karaokeNo: '623429', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2015,
    title: 'ビターバカンス',
    titleKo: '비터 바캉스',
    titleNorm: 'bitter vacance',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2040, songId: 2015, provider: Provider.TJ, karaokeNo: '52804', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2041, songId: 2015, provider: Provider.KY, karaokeNo: '57819', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2042, songId: 2015, provider: Provider.JOYSOUND, karaokeNo: '632140', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2016,
    title: 'ブルーアンビエンス (feat. asmi)',
    titleKo: '블루 앰비언스 (feat. asmi)',
    titleNorm: 'blue ambience feat asmi',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2043, songId: 2016, provider: Provider.TJ, karaokeNo: '68636', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2044, songId: 2016, provider: Provider.KY, karaokeNo: '44824', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2045, songId: 2016, provider: Provider.JOYSOUND, karaokeNo: '499124', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
  {
    id: 2017,
    title: 'GOOD DAY',
    titleKo: 'GOOD DAY',
    titleNorm: 'good day',
    youtubeVideoId: undefined,
    youtubeFetchedAt: undefined,
    primaryArtistId: 2,
    primaryArtist: mrsGreenAppleArtist,
    createdAt: now,
    updatedAt: now,
    karaokeSongs: [
      { id: 2046, songId: 2017, provider: Provider.TJ, karaokeNo: '52974', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
      { id: 2047, songId: 2017, provider: Provider.JOYSOUND, karaokeNo: '641010', providerSongUrl: undefined, lastSeenAt: now, ingestedAt: now, ingestedFrom: 'manual' },
    ],
  },
];
