/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MobileAnonymousLoginDto,
  MobileAuthResponseDto,
  MobileLogoutResponseDto,
  ProfileResponseDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * 새 익명 모바일 사용자 생성 및 토큰 발급
 * @summary 앱 익명 로그인
 */
export const mobileAuthControllerAnonymousLogin = (
    mobileAnonymousLoginDto: MobileAnonymousLoginDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<MobileAuthResponseDto | MobileAuthResponseDto>(
      {url: `/auth/mobile/anonymous`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: mobileAnonymousLoginDto, signal
    },
      );
    }
  


export const getMobileAuthControllerAnonymousLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerAnonymousLogin>>, TError,{data: MobileAnonymousLoginDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerAnonymousLogin>>, TError,{data: MobileAnonymousLoginDto}, TContext> => {

const mutationKey = ['mobileAuthControllerAnonymousLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mobileAuthControllerAnonymousLogin>>, {data: MobileAnonymousLoginDto}> = (props) => {
          const {data} = props ?? {};

          return  mobileAuthControllerAnonymousLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MobileAuthControllerAnonymousLoginMutationResult = NonNullable<Awaited<ReturnType<typeof mobileAuthControllerAnonymousLogin>>>
    export type MobileAuthControllerAnonymousLoginMutationBody = MobileAnonymousLoginDto
    export type MobileAuthControllerAnonymousLoginMutationError = unknown

    /**
 * @summary 앱 익명 로그인
 */
export const useMobileAuthControllerAnonymousLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerAnonymousLogin>>, TError,{data: MobileAnonymousLoginDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof mobileAuthControllerAnonymousLogin>>,
        TError,
        {data: MobileAnonymousLoginDto},
        TContext
      > => {

      const mutationOptions = getMobileAuthControllerAnonymousLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 본문의 Refresh token으로 새 토큰 발급
 * @summary 앱 토큰 갱신
 */
export const mobileAuthControllerRefresh = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<MobileAuthResponseDto | MobileAuthResponseDto>(
      {url: `/auth/mobile/refresh`, method: 'POST', signal
    },
      );
    }
  


export const getMobileAuthControllerRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerRefresh>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerRefresh>>, TError,void, TContext> => {

const mutationKey = ['mobileAuthControllerRefresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mobileAuthControllerRefresh>>, void> = () => {
          

          return  mobileAuthControllerRefresh()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MobileAuthControllerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof mobileAuthControllerRefresh>>>
    
    export type MobileAuthControllerRefreshMutationError = unknown

    /**
 * @summary 앱 토큰 갱신
 */
export const useMobileAuthControllerRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerRefresh>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof mobileAuthControllerRefresh>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getMobileAuthControllerRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 모바일 클라이언트에서 현재 사용자 정보 조회
 * @summary 앱 프로필 조회
 */
export const mobileAuthControllerGetProfile = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<ProfileResponseDto>(
      {url: `/auth/mobile/profile`, method: 'GET', signal
    },
      );
    }
  



export const getMobileAuthControllerGetProfileQueryKey = () => {
    return [
    `/auth/mobile/profile`
    ] as const;
    }

    
export const getMobileAuthControllerGetProfileQueryOptions = <TData = Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMobileAuthControllerGetProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>> = ({ signal }) => mobileAuthControllerGetProfile(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MobileAuthControllerGetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>>
export type MobileAuthControllerGetProfileQueryError = unknown


export function useMobileAuthControllerGetProfile<TData = Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMobileAuthControllerGetProfile<TData = Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMobileAuthControllerGetProfile<TData = Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 앱 프로필 조회
 */

export function useMobileAuthControllerGetProfile<TData = Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileAuthControllerGetProfile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMobileAuthControllerGetProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 모바일 토큰 무효화
 * @summary 앱 로그아웃
 */
export const mobileAuthControllerLogout = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<MobileLogoutResponseDto | MobileLogoutResponseDto>(
      {url: `/auth/mobile/logout`, method: 'POST', signal
    },
      );
    }
  


export const getMobileAuthControllerLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['mobileAuthControllerLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mobileAuthControllerLogout>>, void> = () => {
          

          return  mobileAuthControllerLogout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MobileAuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof mobileAuthControllerLogout>>>
    
    export type MobileAuthControllerLogoutMutationError = unknown

    /**
 * @summary 앱 로그아웃
 */
export const useMobileAuthControllerLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mobileAuthControllerLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof mobileAuthControllerLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getMobileAuthControllerLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    