/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ArtistDetailResponseDto,
  ErrorResponseDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * slug 로 아티스트 상세 정보를 조회합니다.
 * @summary 아티스트 상세 조회 (slug)
 */
export const artistsControllerFindBySlug = (
    slug: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<ArtistDetailResponseDto>(
      {url: `/artists/${slug}`, method: 'GET', signal
    },
      );
    }
  



export const getArtistsControllerFindBySlugQueryKey = (slug?: string,) => {
    return [
    `/artists/${slug}`
    ] as const;
    }

    
export const getArtistsControllerFindBySlugQueryOptions = <TData = Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError = ErrorResponseDto>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArtistsControllerFindBySlugQueryKey(slug);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof artistsControllerFindBySlug>>> = ({ signal }) => artistsControllerFindBySlug(slug, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArtistsControllerFindBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof artistsControllerFindBySlug>>>
export type ArtistsControllerFindBySlugQueryError = ErrorResponseDto


export function useArtistsControllerFindBySlug<TData = Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError = ErrorResponseDto>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerFindBySlug>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerFindBySlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerFindBySlug<TData = Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError = ErrorResponseDto>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerFindBySlug>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerFindBySlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerFindBySlug<TData = Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError = ErrorResponseDto>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 아티스트 상세 조회 (slug)
 */

export function useArtistsControllerFindBySlug<TData = Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError = ErrorResponseDto>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindBySlug>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArtistsControllerFindBySlugQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




