/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ArtistDetailResponseDto,
  ArtistListResponseDto,
  ArtistWithYoutubeListResponseDto,
  YoutubeChannelUpdateDto,
  YoutubeChannelUpdateResponseDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * 전체 아티스트를 반환합니다.
 * @summary 아티스트 목록 조회
 */
export const artistsControllerFindAll = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<ArtistListResponseDto>(
      {url: `/artists`, method: 'GET', signal
    },
      );
    }
  



export const getArtistsControllerFindAllQueryKey = () => {
    return [
    `/artists`
    ] as const;
    }

    
export const getArtistsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof artistsControllerFindAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArtistsControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof artistsControllerFindAll>>> = ({ signal }) => artistsControllerFindAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArtistsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof artistsControllerFindAll>>>
export type ArtistsControllerFindAllQueryError = unknown


export function useArtistsControllerFindAll<TData = Awaited<ReturnType<typeof artistsControllerFindAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerFindAll<TData = Awaited<ReturnType<typeof artistsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerFindAll<TData = Awaited<ReturnType<typeof artistsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 아티스트 목록 조회
 */

export function useArtistsControllerFindAll<TData = Awaited<ReturnType<typeof artistsControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArtistsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 전체 아티스트를 YouTube 채널 정보와 함께 반환합니다. 구독자 수 기준으로 정렬됩니다.
 * @summary 아티스트 목록 조회 (YouTube 정보 포함)
 */
export const artistsControllerFindAllWithYoutube = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<ArtistWithYoutubeListResponseDto>(
      {url: `/artists/with-youtube`, method: 'GET', signal
    },
      );
    }
  



export const getArtistsControllerFindAllWithYoutubeQueryKey = () => {
    return [
    `/artists/with-youtube`
    ] as const;
    }

    
export const getArtistsControllerFindAllWithYoutubeQueryOptions = <TData = Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArtistsControllerFindAllWithYoutubeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>> = ({ signal }) => artistsControllerFindAllWithYoutube(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArtistsControllerFindAllWithYoutubeQueryResult = NonNullable<Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>>
export type ArtistsControllerFindAllWithYoutubeQueryError = unknown


export function useArtistsControllerFindAllWithYoutube<TData = Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerFindAllWithYoutube<TData = Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerFindAllWithYoutube<TData = Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 아티스트 목록 조회 (YouTube 정보 포함)
 */

export function useArtistsControllerFindAllWithYoutube<TData = Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindAllWithYoutube>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArtistsControllerFindAllWithYoutubeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 숫자는 ID로, 문자열은 alias 로 판단하여 해당 아티스트 정보를 반환합니다.
 * @summary 아티스트 상세 조회 (ID 또는 alias)
 */
export const artistsControllerFindByIdOrAlias = (
    identifier: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<ArtistDetailResponseDto>(
      {url: `/artists/${identifier}`, method: 'GET', signal
    },
      );
    }
  



export const getArtistsControllerFindByIdOrAliasQueryKey = (identifier?: string,) => {
    return [
    `/artists/${identifier}`
    ] as const;
    }

    
export const getArtistsControllerFindByIdOrAliasQueryOptions = <TData = Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError = void>(identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArtistsControllerFindByIdOrAliasQueryKey(identifier);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>> = ({ signal }) => artistsControllerFindByIdOrAlias(identifier, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(identifier), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArtistsControllerFindByIdOrAliasQueryResult = NonNullable<Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>>
export type ArtistsControllerFindByIdOrAliasQueryError = void


export function useArtistsControllerFindByIdOrAlias<TData = Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError = void>(
 identifier: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerFindByIdOrAlias<TData = Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError = void>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>,
          TError,
          Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArtistsControllerFindByIdOrAlias<TData = Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError = void>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 아티스트 상세 조회 (ID 또는 alias)
 */

export function useArtistsControllerFindByIdOrAlias<TData = Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError = void>(
 identifier: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof artistsControllerFindByIdOrAlias>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArtistsControllerFindByIdOrAliasQueryOptions(identifier,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 선택한 아티스트에 YouTube 채널 ID 또는 @handle 을 연결합니다.
 * @summary 아티스트 YouTube 채널 정보 업데이트
 */
export const artistsControllerUpdateYoutubeChannel = (
    alias: string,
    youtubeChannelUpdateDto: YoutubeChannelUpdateDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<YoutubeChannelUpdateResponseDto | YoutubeChannelUpdateResponseDto>(
      {url: `/artists/${alias}/youtube-channel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: youtubeChannelUpdateDto, signal
    },
      );
    }
  


export const getArtistsControllerUpdateYoutubeChannelMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof artistsControllerUpdateYoutubeChannel>>, TError,{alias: string;data: YoutubeChannelUpdateDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof artistsControllerUpdateYoutubeChannel>>, TError,{alias: string;data: YoutubeChannelUpdateDto}, TContext> => {

const mutationKey = ['artistsControllerUpdateYoutubeChannel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof artistsControllerUpdateYoutubeChannel>>, {alias: string;data: YoutubeChannelUpdateDto}> = (props) => {
          const {alias,data} = props ?? {};

          return  artistsControllerUpdateYoutubeChannel(alias,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ArtistsControllerUpdateYoutubeChannelMutationResult = NonNullable<Awaited<ReturnType<typeof artistsControllerUpdateYoutubeChannel>>>
    export type ArtistsControllerUpdateYoutubeChannelMutationBody = YoutubeChannelUpdateDto
    export type ArtistsControllerUpdateYoutubeChannelMutationError = void

    /**
 * @summary 아티스트 YouTube 채널 정보 업데이트
 */
export const useArtistsControllerUpdateYoutubeChannel = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof artistsControllerUpdateYoutubeChannel>>, TError,{alias: string;data: YoutubeChannelUpdateDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof artistsControllerUpdateYoutubeChannel>>,
        TError,
        {alias: string;data: YoutubeChannelUpdateDto},
        TContext
      > => {

      const mutationOptions = getArtistsControllerUpdateYoutubeChannelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    