version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: song-jpop-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: jpop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - jpop_postgres_data:/var/lib/postgresql/data

volumes:
  jpop_postgres_data:
