/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface AnonymousLoginDto {
  /** 기기 고유 ID (UUID v4). 없으면 서버에서 새로 생성 */
  deviceId?: string;
}
