/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface ApiResponseMeta {
  /** 전체 개수 */
  total?: number;
  /** 현재 페이지 */
  page?: number;
  /** 페이지 크기 */
  limit?: number;
  /** 더 있는지 */
  hasMore?: boolean;
}
