/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { YoutubeInfoDto } from './youtubeInfoDto';
import type { SpotifyInfoDto } from './spotifyInfoDto';
import type { SongDto } from './songDto';

export interface ArtistDetailsDto {
  id: number;
  name: string;
  nameKo: string;
  /** 아티스트 슬러그 */
  slug?: string;
  /** 아티스트의 대표 카탈로그 */
  homeCatalog?: string;
  thumbnailDefault?: string;
  thumbnailMedium?: string;
  thumbnailHigh?: string;
  songCount: number;
  /** TJ에서 사용하는 아티스트 이름 */
  tjName?: string;
  youtube?: YoutubeInfoDto;
  spotify?: SpotifyInfoDto;
  /** 아티스트의 곡 목록 */
  songs?: SongDto[];
}
