/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface ArtistDto {
  id: number;
  name: string;
  nameKo: string;
  /** @nullable */
  alias?: string | null;
  /** @nullable */
  thumbnailDefault?: string | null;
  /** @nullable */
  thumbnailMedium?: string | null;
  /** @nullable */
  thumbnailHigh?: string | null;
  /**
   * 연결된 YouTube 채널 ID
   * @nullable
   */
  youtubeChannelId?: string | null;
  /**
   * TJ 노래방 곡 추가 요청 URL
   * @nullable
   */
  tjSongRequestUrl?: string | null;
}
