/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ArtistSlugGroupDto } from './artistSlugGroupDto';
import type { YoutubeInfoDto } from './youtubeInfoDto';

export interface ArtistDetailsDto {
  id: number;
  name: string;
  nameKo: string;
  slug?: string;
  /** 아티스트의 대표 카탈로그 */
  homeCatalog?: string;
  thumbnailDefault?: string;
  thumbnailMedium?: string;
  thumbnailHigh?: string;
  songCount: number;
  /** TJ 노래방 곡 추가 요청 URL */
  tjSongRequestUrl?: string;
  slugGroup?: ArtistSlugGroupDto;
  youtube?: YoutubeInfoDto;
}
