/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ArtistDatailsDtoAliasGroup } from './artistDatailsDtoAliasGroup';
import type { ArtistDatailsDtoYoutube } from './artistDatailsDtoYoutube';

export interface ArtistDatailsDto {
  id: number;
  name: string;
  nameKo: string;
  /** @nullable */
  alias?: string | null;
  /** @nullable */
  thumbnailDefault?: string | null;
  /** @nullable */
  thumbnailMedium?: string | null;
  /** @nullable */
  thumbnailHigh?: string | null;
  songCount: number;
  /** @nullable */
  aliasGroup?: ArtistDatailsDtoAliasGroup;
  /** @nullable */
  youtube?: ArtistDatailsDtoYoutube;
}
