/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ArtistsControllerFindAllSort = typeof ArtistsControllerFindAllSort[keyof typeof ArtistsControllerFindAllSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArtistsControllerFindAllSort = {
  id_desc: 'id_desc',
  name_asc: 'name_asc',
  name_desc: 'name_desc',
  subscriber_desc: 'subscriber_desc',
  subscriber_asc: 'subscriber_asc',
  song_count_asc: 'song_count_asc',
  song_count_desc: 'song_count_desc',
} as const;
