/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ArtistWithYoutubeDtoYoutube } from './artistWithYoutubeDtoYoutube';

export interface ArtistWithYoutubeDto {
  id: number;
  name: string;
  nameKo: string;
  /** @nullable */
  alias?: string | null;
  /** @nullable */
  youtube?: ArtistWithYoutubeDtoYoutube;
}
