/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ArtistsControllerFindAllDetailsSort } from './artistsControllerFindAllDetailsSort';

export type ArtistsControllerFindAllDetailsParams = {
/**
 * 정렬 기준 (id_desc, name_asc, name_desc, subscriber_desc, subscriber_asc, song_count_asc, song_count_desc)
 */
sort?: ArtistsControllerFindAllDetailsSort;
/**
 * 페이지 번호 (기본값: 1)
 */
page?: string;
/**
 * 페이지당 항목 수 (기본값: 20)
 */
limit?: string;
};
