/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface AuthResponseDto {
  /** Access token 만료 시간 (초) */
  expiresIn: number;
  /** 쿠키 설정 성공 여부 */
  success: boolean;
  /** 모바일 클라이언트 요청 시 본문으로 반환되는 Access Token */
  accessToken?: string;
  /** 모바일 클라이언트 요청 시 본문으로 반환되는 Refresh Token */
  refreshToken?: string;
}
