/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface CreateReportDto {
  /** 신고 대상 곡 ID */
  songId?: number;
  /** 신고 대상 아티스트 ID */
  artistId?: number;
  /** 신고 제목 */
  title: string;
  /** 신고 내용 */
  content: string;
  /** 답변 받을 이메일 */
  email?: string;
}
