/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface ErrorResponseDto {
  /** HTTP 상태 코드 */
  statusCode: number;
  /** 오류 메시지 */
  message: string;
  /** 오류 유형(선택) */
  error?: string;
}
