/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface MobileAnonymousLoginDto {
  /** 기기 고유 ID */
  deviceId: string;
  /** 클라이언트에서 생성한 nonce. timestamp 등 재사용되지 않는 값 사용 권장 */
  nonce: string;
  /** HMAC-SHA256(deviceSecret, nonce)의 16진수 문자열. 기존 기기는 필수 */
  signature?: string;
}
