/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface MobileLogoutResponseDto {
  /** 로그아웃 처리 성공 여부 */
  success: boolean;
}
