/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface OembedDataDto {
  title: string;
  author_name: string;
  author_url: string;
  type: string;
  height?: number;
  width?: number;
  version: string;
  provider_name: string;
  provider_url: string;
  thumbnail_height?: number;
  thumbnail_width?: number;
  thumbnail_url?: string;
  html?: string;
}
