/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type ReportDtoStatus = typeof ReportDtoStatus[keyof typeof ReportDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportDtoStatus = {
  PENDING: 'PENDING',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
} as const;
