/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface SaveSearchClickDto {
  /** 검색어 */
  query?: string;
  /** 검색 URL (링크 검색) */
  url?: string;
  /** 클릭한 아티스트 ID */
  artistId?: number;
  /** 클릭한 곡 ID */
  songId?: number;
  /** 클릭 출처 (search, autocomplete, home, popular_song, tj_recent, tj_best 등) */
  source?: string;
}
