/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface SearchSuggestionSuggestionDto {
  /** 추천 검색어 텍스트 */
  title: string;
  /** 추천 출처 (예: 최근 검색, 추천 등) */
  source: string;
}
