/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface SearchSuggestionPlaylistDto {
  /** 플레이리스트 ID */
  id: number;
  /** 플레이리스트 제목 */
  title: string;
  /** 플레이리스트 썸네일 */
  thumbnail?: string;
}
