/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { SearchResultDtoType } from './searchResultDtoType';
import type { ArtistDetailsDto } from './artistDetailsDto';
import type { SongDto } from './songDto';

export interface SearchResultDto {
  /** 검색 결과 타입 */
  type: SearchResultDtoType;
  artist?: ArtistDetailsDto;
  song?: SongDto;
}
