/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { SearchSuggestionCardDto } from './searchSuggestionCardDto';

export interface SearchSuggestionsDataDto {
  /** 카드 UI로 렌더링 가능한 추천 아이템 목록 */
  cards: SearchSuggestionCardDto[];
}
