/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type SearchControllerSearchByKaraokeNoParams = {
/**
 * 노래방 번호
 */
no: string;
/**
 * 노래방 기기 (예: TJ, KY)
 */
provider?: string;
};
