/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { TjSongDto } from './tjSongDto';
import type { BestSongProposeDto } from './bestSongProposeDto';

export interface SearchSuggestionSongDto {
  /** 곡 ID */
  id: number;
  /** 곡 제목 */
  title: string;
  /** 곡 한글 제목 */
  titleKo?: string;
  /** 곡 일본어 제목 */
  titleJa?: string;
  /** 곡 로마자 제목 */
  titleLatin?: string;
  /** 곡의 대표 아티스트명 */
  artistName: string;
  /** 곡의 대표 아티스트 slug */
  artistSlug?: string;
  /** TJ 노래방 곡 정보 */
  tjSong?: TjSongDto;
  /** 곡 썸네일 */
  thumbnail?: string;
  /** 3개월 이내 가장 추천수가 높은 곡 추천 정보 */
  bestSongPropose?: BestSongProposeDto;
}
