/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { SearchSuggestionSuggestionDto } from './searchSuggestionSuggestionDto';
import type { SearchSuggestionArtistDto } from './searchSuggestionArtistDto';
import type { SearchSuggestionSongDto } from './searchSuggestionSongDto';
import type { SearchSuggestionPlaylistDto } from './searchSuggestionPlaylistDto';

export interface SearchSuggestionCardDto {
  /** 추천 검색어 카드 */
  suggestion?: SearchSuggestionSuggestionDto;
  /** 아티스트 카드 */
  artist?: SearchSuggestionArtistDto;
  /** 곡 카드 */
  song?: SearchSuggestionSongDto;
  /** 플레이리스트 카드 */
  playlist?: SearchSuggestionPlaylistDto;
}
