/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface SearchSuggestionArtistDto {
  /** 아티스트 ID */
  id: number;
  /** 아티스트 식별 슬러그 */
  slug?: string;
  /** 아티스트 제목 */
  title: string;
  /** 아티스트 한글 제목 */
  titleKo?: string;
  /** 아티스트 썸네일 */
  thumbnail?: string;
}
