/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 검색 결과 타입
 */
export type SearchResultDtoType = typeof SearchResultDtoType[keyof typeof SearchResultDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchResultDtoType = {
  artist: 'artist',
  song: 'song',
} as const;
