/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type SearchResponseDtoMeta = {
  total: number;
  page: number;
  limit: number;
  hasMore: boolean;
};
