/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type SongsControllerFindAllParams = {
/**
 * 검색어 (제목으로 검색)
 */
q?: string;
/**
 * 아티스트 ID로 필터링
 */
artistId?: string;
};
