/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { ArtistSongDto } from './artistSongDto';
import type { TjSongDto } from './tjSongDto';
import type { SpotifyTrackInfoDto } from './spotifyTrackInfoDto';
import type { YoutubeVideoInfoDto } from './youtubeVideoInfoDto';
import type { BestSongProposeDto } from './bestSongProposeDto';

export interface SongDto {
  id: number;
  title: string;
  titleKo?: string;
  titleJa?: string;
  titleLatin?: string;
  titleJaPronu?: string;
  titleLatinPronu?: string;
  catalog?: string;
  artists: ArtistSongDto[];
  tjSong?: TjSongDto;
  thumbnailDefault?: string;
  thumbnailMedium?: string;
  thumbnailHigh?: string;
  /** Spotify 트랙 정보 */
  spotify?: SpotifyTrackInfoDto;
  /** YouTube 비디오 정보 */
  youtube?: YoutubeVideoInfoDto;
  /** 3개월 이내 가장 추천수가 높은 곡 추천 정보 */
  bestSongPropose?: BestSongProposeDto;
}
