/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export type SongsControllerFindByArtistIdParams = {
/**
 * 페이지 번호 (기본값: 1)
 */
page?: string;
/**
 * 페이지당 항목 수 (기본값: 20)
 */
limit?: string;
};
