/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

export interface TjSongDto {
  id: string;
  title: string;
  artist?: string;
  lyricist?: string;
  composer?: string;
  publishdate?: string;
  isMR: boolean;
  isMV: boolean;
  isOver60: boolean;
}
