/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 재생성할 인덱스 범위
 */
export type TypesenseReindexRequestDtoTarget = typeof TypesenseReindexRequestDtoTarget[keyof typeof TypesenseReindexRequestDtoTarget];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypesenseReindexRequestDtoTarget = {
  artists: 'artists',
  songs: 'songs',
  all: 'all',
} as const;
