/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { TypesenseReindexRequestDtoTarget } from './typesenseReindexRequestDtoTarget';

export interface TypesenseReindexRequestDto {
  /** 재생성할 인덱스 범위 */
  target: TypesenseReindexRequestDtoTarget;
  /** 특정 artistId 이하만 인덱싱할 때 사용 (미지정 시 272까지 처리) */
  maxArtistId?: number;
}
