/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import type { SongDto } from './songDto';
import type { YoutubeOembedDataDto } from './youtubeOembedDataDto';

export interface YoutubeSongSearchResponseDto {
  /** DB에서 찾은 곡 정보 */
  song?: SongDto;
  /** 유튜브 oEmbed 데이터 (DB에서 곡을 찾지 못한 경우) */
  youtube?: YoutubeOembedDataDto;
  message: string;
}
