/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  SongDetailResponseDto,
  SongListResponseDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * 아티스트 ID로 해당 아티스트의 곡 목록을 조회합니다.
 * @summary 특정 아티스트의 곡 목록 조회
 */
export const songsControllerFindByArtistId = (
    artistId: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<SongListResponseDto>(
      {url: `/songs/artist/${artistId}`, method: 'GET', signal
    },
      );
    }
  



export const getSongsControllerFindByArtistIdQueryKey = (artistId?: number,) => {
    return [
    `/songs/artist/${artistId}`
    ] as const;
    }

    
export const getSongsControllerFindByArtistIdQueryOptions = <TData = Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError = ErrorResponseDto>(artistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSongsControllerFindByArtistIdQueryKey(artistId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof songsControllerFindByArtistId>>> = ({ signal }) => songsControllerFindByArtistId(artistId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(artistId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SongsControllerFindByArtistIdQueryResult = NonNullable<Awaited<ReturnType<typeof songsControllerFindByArtistId>>>
export type SongsControllerFindByArtistIdQueryError = ErrorResponseDto


export function useSongsControllerFindByArtistId<TData = Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError = ErrorResponseDto>(
 artistId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindByArtistId>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindByArtistId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindByArtistId<TData = Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError = ErrorResponseDto>(
 artistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindByArtistId>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindByArtistId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindByArtistId<TData = Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError = ErrorResponseDto>(
 artistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 특정 아티스트의 곡 목록 조회
 */

export function useSongsControllerFindByArtistId<TData = Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError = ErrorResponseDto>(
 artistId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindByArtistId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSongsControllerFindByArtistIdQueryOptions(artistId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 곡 ID로 단일 곡 상세 정보를 조회합니다.
 * @summary 곡 상세 조회
 */
export const songsControllerFindOne = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<SongDetailResponseDto>(
      {url: `/songs/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getSongsControllerFindOneQueryKey = (id?: number,) => {
    return [
    `/songs/${id}`
    ] as const;
    }

    
export const getSongsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSongsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof songsControllerFindOne>>> = ({ signal }) => songsControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SongsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof songsControllerFindOne>>>
export type SongsControllerFindOneQueryError = ErrorResponseDto


export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 곡 상세 조회
 */

export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSongsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




