/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  SongDetailResponseDto,
  SongListResponseDto,
  SongsControllerFindBySortParams
} from '.././models';

import { customFetch } from '../../client';




/**
 * 정렬 옵션에 따라 곡 목록을 조회합니다.
- recent: 최근에 나온 곡 (TJ 발매일자 최신순)
 * @summary 곡 목록 조회 (정렬 옵션)
 */
export const songsControllerFindBySort = (
    params?: SongsControllerFindBySortParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<SongListResponseDto>(
      {url: `/songs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSongsControllerFindBySortQueryKey = (params?: SongsControllerFindBySortParams,) => {
    return [
    `/songs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSongsControllerFindBySortQueryOptions = <TData = Awaited<ReturnType<typeof songsControllerFindBySort>>, TError = ErrorResponseDto>(params?: SongsControllerFindBySortParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindBySort>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSongsControllerFindBySortQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof songsControllerFindBySort>>> = ({ signal }) => songsControllerFindBySort(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindBySort>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SongsControllerFindBySortQueryResult = NonNullable<Awaited<ReturnType<typeof songsControllerFindBySort>>>
export type SongsControllerFindBySortQueryError = ErrorResponseDto


export function useSongsControllerFindBySort<TData = Awaited<ReturnType<typeof songsControllerFindBySort>>, TError = ErrorResponseDto>(
 params: undefined |  SongsControllerFindBySortParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindBySort>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindBySort>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindBySort>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindBySort<TData = Awaited<ReturnType<typeof songsControllerFindBySort>>, TError = ErrorResponseDto>(
 params?: SongsControllerFindBySortParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindBySort>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindBySort>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindBySort>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindBySort<TData = Awaited<ReturnType<typeof songsControllerFindBySort>>, TError = ErrorResponseDto>(
 params?: SongsControllerFindBySortParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindBySort>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 곡 목록 조회 (정렬 옵션)
 */

export function useSongsControllerFindBySort<TData = Awaited<ReturnType<typeof songsControllerFindBySort>>, TError = ErrorResponseDto>(
 params?: SongsControllerFindBySortParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindBySort>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSongsControllerFindBySortQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 곡 ID로 단일 곡 상세 정보를 조회합니다.
 * @summary 단일 곡 조회
 */
export const songsControllerFindOne = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<SongDetailResponseDto>(
      {url: `/songs/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getSongsControllerFindOneQueryKey = (id?: number,) => {
    return [
    `/songs/${id}`
    ] as const;
    }

    
export const getSongsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSongsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof songsControllerFindOne>>> = ({ signal }) => songsControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SongsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof songsControllerFindOne>>>
export type SongsControllerFindOneQueryError = ErrorResponseDto


export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 단일 곡 조회
 */

export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = ErrorResponseDto>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSongsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




