/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SongsControllerFindAllParams
} from '.././models';

import { customFetch } from '../../client';




/**
 * @summary 곡 목록 조회 (검색 및 필터링)
 */
export const songsControllerFindAll = (
    params?: SongsControllerFindAllParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<void>(
      {url: `/songs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSongsControllerFindAllQueryKey = (params?: SongsControllerFindAllParams,) => {
    return [
    `/songs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSongsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof songsControllerFindAll>>, TError = unknown>(params?: SongsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSongsControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof songsControllerFindAll>>> = ({ signal }) => songsControllerFindAll(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SongsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof songsControllerFindAll>>>
export type SongsControllerFindAllQueryError = unknown


export function useSongsControllerFindAll<TData = Awaited<ReturnType<typeof songsControllerFindAll>>, TError = unknown>(
 params: undefined |  SongsControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindAll<TData = Awaited<ReturnType<typeof songsControllerFindAll>>, TError = unknown>(
 params?: SongsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindAll<TData = Awaited<ReturnType<typeof songsControllerFindAll>>, TError = unknown>(
 params?: SongsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 곡 목록 조회 (검색 및 필터링)
 */

export function useSongsControllerFindAll<TData = Awaited<ReturnType<typeof songsControllerFindAll>>, TError = unknown>(
 params?: SongsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSongsControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary 곡 상세 조회
 */
export const songsControllerFindOne = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<void>(
      {url: `/songs/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getSongsControllerFindOneQueryKey = (id?: number,) => {
    return [
    `/songs/${id}`
    ] as const;
    }

    
export const getSongsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = void>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSongsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof songsControllerFindOne>>> = ({ signal }) => songsControllerFindOne(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SongsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof songsControllerFindOne>>>
export type SongsControllerFindOneQueryError = void


export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = void>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof songsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof songsControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 곡 상세 조회
 */

export function useSongsControllerFindOne<TData = Awaited<ReturnType<typeof songsControllerFindOne>>, TError = void>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof songsControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSongsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




