/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  SearchControllerGetSearchSuggestionsParams,
  SearchControllerSearchParams,
  SearchControllerSearchSongByYoutubeUrlParams,
  SearchResponseDto,
  SearchSuggestionsResponseDto,
  YoutubeSongSearchResponseDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * 아티스트와 곡을 통합 검색합니다.
 * @summary 통합 검색
 */
export const searchControllerSearch = (
    params: SearchControllerSearchParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<SearchResponseDto>(
      {url: `/search`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchControllerSearchQueryKey = (params?: SearchControllerSearchParams,) => {
    return [
    `/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchControllerSearchQueryOptions = <TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = ErrorResponseDto>(params: SearchControllerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchControllerSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerSearch>>> = ({ signal }) => searchControllerSearch(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchControllerSearchQueryResult = NonNullable<Awaited<ReturnType<typeof searchControllerSearch>>>
export type SearchControllerSearchQueryError = ErrorResponseDto


export function useSearchControllerSearch<TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = ErrorResponseDto>(
 params: SearchControllerSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof searchControllerSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchControllerSearch<TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = ErrorResponseDto>(
 params: SearchControllerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof searchControllerSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchControllerSearch<TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = ErrorResponseDto>(
 params: SearchControllerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 통합 검색
 */

export function useSearchControllerSearch<TData = Awaited<ReturnType<typeof searchControllerSearch>>, TError = ErrorResponseDto>(
 params: SearchControllerSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearch>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchControllerSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 검색어를 기반으로 자동완성 결과(아티스트, 곡)를 반환합니다.
 * @summary 검색 자동완성
 */
export const searchControllerGetSearchSuggestions = (
    params?: SearchControllerGetSearchSuggestionsParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<SearchSuggestionsResponseDto>(
      {url: `/search/suggestions`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchControllerGetSearchSuggestionsQueryKey = (params?: SearchControllerGetSearchSuggestionsParams,) => {
    return [
    `/search/suggestions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchControllerGetSearchSuggestionsQueryOptions = <TData = Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError = ErrorResponseDto>(params?: SearchControllerGetSearchSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchControllerGetSearchSuggestionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>> = ({ signal }) => searchControllerGetSearchSuggestions(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchControllerGetSearchSuggestionsQueryResult = NonNullable<Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>>
export type SearchControllerGetSearchSuggestionsQueryError = ErrorResponseDto


export function useSearchControllerGetSearchSuggestions<TData = Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError = ErrorResponseDto>(
 params: undefined |  SearchControllerGetSearchSuggestionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchControllerGetSearchSuggestions<TData = Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError = ErrorResponseDto>(
 params?: SearchControllerGetSearchSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchControllerGetSearchSuggestions<TData = Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError = ErrorResponseDto>(
 params?: SearchControllerGetSearchSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 검색 자동완성
 */

export function useSearchControllerGetSearchSuggestions<TData = Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError = ErrorResponseDto>(
 params?: SearchControllerGetSearchSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSearchSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchControllerGetSearchSuggestionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * YouTube 링크에서 제목을 추출하고 가장 일치하는 곡 정보를 반환합니다. DB에서 곡을 찾지 못한 경우 유튜브 정보를 반환합니다.
 * @summary 유튜브 URL로 단일곡 검색
 */
export const searchControllerSearchSongByYoutubeUrl = (
    params: SearchControllerSearchSongByYoutubeUrlParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<YoutubeSongSearchResponseDto>(
      {url: `/search/youtube`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchControllerSearchSongByYoutubeUrlQueryKey = (params?: SearchControllerSearchSongByYoutubeUrlParams,) => {
    return [
    `/search/youtube`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchControllerSearchSongByYoutubeUrlQueryOptions = <TData = Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError = ErrorResponseDto>(params: SearchControllerSearchSongByYoutubeUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchControllerSearchSongByYoutubeUrlQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>> = ({ signal }) => searchControllerSearchSongByYoutubeUrl(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchControllerSearchSongByYoutubeUrlQueryResult = NonNullable<Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>>
export type SearchControllerSearchSongByYoutubeUrlQueryError = ErrorResponseDto


export function useSearchControllerSearchSongByYoutubeUrl<TData = Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError = ErrorResponseDto>(
 params: SearchControllerSearchSongByYoutubeUrlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>,
          TError,
          Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchControllerSearchSongByYoutubeUrl<TData = Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError = ErrorResponseDto>(
 params: SearchControllerSearchSongByYoutubeUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>,
          TError,
          Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchControllerSearchSongByYoutubeUrl<TData = Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError = ErrorResponseDto>(
 params: SearchControllerSearchSongByYoutubeUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 유튜브 URL로 단일곡 검색
 */

export function useSearchControllerSearchSongByYoutubeUrl<TData = Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError = ErrorResponseDto>(
 params: SearchControllerSearchSongByYoutubeUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerSearchSongByYoutubeUrl>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchControllerSearchSongByYoutubeUrlQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




