/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  SearchControllerGetSongByYoutubeUrlParams,
  YoutubeSongSearchResponseDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * YouTube 링크에서 제목을 추출하고 가장 일치하는 곡 정보를 반환합니다.
 * @summary YouTube URL로 곡 정보 조회
 */
export const searchControllerGetSongByYoutubeUrl = (
    params: SearchControllerGetSongByYoutubeUrlParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<YoutubeSongSearchResponseDto>(
      {url: `/search/youtube`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getSearchControllerGetSongByYoutubeUrlQueryKey = (params?: SearchControllerGetSongByYoutubeUrlParams,) => {
    return [
    `/search/youtube`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchControllerGetSongByYoutubeUrlQueryOptions = <TData = Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError = ErrorResponseDto>(params: SearchControllerGetSongByYoutubeUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchControllerGetSongByYoutubeUrlQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>> = ({ signal }) => searchControllerGetSongByYoutubeUrl(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchControllerGetSongByYoutubeUrlQueryResult = NonNullable<Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>>
export type SearchControllerGetSongByYoutubeUrlQueryError = ErrorResponseDto


export function useSearchControllerGetSongByYoutubeUrl<TData = Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError = ErrorResponseDto>(
 params: SearchControllerGetSongByYoutubeUrlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchControllerGetSongByYoutubeUrl<TData = Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError = ErrorResponseDto>(
 params: SearchControllerGetSongByYoutubeUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>,
          TError,
          Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchControllerGetSongByYoutubeUrl<TData = Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError = ErrorResponseDto>(
 params: SearchControllerGetSongByYoutubeUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary YouTube URL로 곡 정보 조회
 */

export function useSearchControllerGetSongByYoutubeUrl<TData = Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError = ErrorResponseDto>(
 params: SearchControllerGetSongByYoutubeUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchControllerGetSongByYoutubeUrl>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchControllerGetSongByYoutubeUrlQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




