/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * 노래방 검색 API
 * 노래방 검색 서비스 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  TypesenseReindexRequestDto
} from '.././models';

import { customFetch } from '../../client';




/**
 * 아티스트/곡 인덱스를 Typesense에 다시 생성합니다.
 * @summary Typesense 인덱스 재생성
 */
export const typesenseAdminControllerReindexCollections = (
    typesenseReindexRequestDto: TypesenseReindexRequestDto,
 signal?: AbortSignal
) => {
      
      
      return customFetch<void>(
      {url: `/typesense/reindex`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: typesenseReindexRequestDto, signal
    },
      );
    }
  


export const getTypesenseAdminControllerReindexCollectionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof typesenseAdminControllerReindexCollections>>, TError,{data: TypesenseReindexRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof typesenseAdminControllerReindexCollections>>, TError,{data: TypesenseReindexRequestDto}, TContext> => {

const mutationKey = ['typesenseAdminControllerReindexCollections'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof typesenseAdminControllerReindexCollections>>, {data: TypesenseReindexRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  typesenseAdminControllerReindexCollections(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TypesenseAdminControllerReindexCollectionsMutationResult = NonNullable<Awaited<ReturnType<typeof typesenseAdminControllerReindexCollections>>>
    export type TypesenseAdminControllerReindexCollectionsMutationBody = TypesenseReindexRequestDto
    export type TypesenseAdminControllerReindexCollectionsMutationError = unknown

    /**
 * @summary Typesense 인덱스 재생성
 */
export const useTypesenseAdminControllerReindexCollections = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof typesenseAdminControllerReindexCollections>>, TError,{data: TypesenseReindexRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof typesenseAdminControllerReindexCollections>>,
        TError,
        {data: TypesenseReindexRequestDto},
        TContext
      > => {

      const mutationOptions = getTypesenseAdminControllerReindexCollectionsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    